In [3]:
import numpy as np
#Q1
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [2]:
# Q2
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
#yes, there will be a difference in the data types of the elements present in the list_ variable and the array_list variable after the change. 
#The array_list variable will have elements of integer data type (int), whereas the list_ variable contains elements of string data type (str).

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Q3
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [6]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Q4
# (i) Shape of num_array
shape = num_array.shape
print("(i) Shape of num_array:", shape)

# (ii) Size of num_array
size = num_array.size
print("(ii) Size of num_array:", size)


(i) Shape of num_array: (2, 3)
(ii) Size of num_array: 6


In [7]:
# Q5
# Creating a numpy array of zeros with shape (3,3)
zeros_array = np.zeros((3, 3))
print("Zeros array:")
print(zeros_array)

Zeros array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:

# Q6
# Creating an identity matrix of shape (5,5)
identity_matrix = np.identity(5)
print("Identity matrix:")
print(identity_matrix)

Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
